# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6db086d75a63d72926aa9c42cd5c16825c99d7e6277b208a7662674efd8ac5637f29a545f79848ec3a9f63f84fd98b79d763d081a89a56740d40e84152c249a

test:
  secret_key_base: bbedc026024e6cb4cd18a2766a295bd21c9504e29bcb8e26d01131dd3a82e8c47b9f67e3cb2be6158afd2122b82e866bb17f1c1a9fbe88b1478c775341218e5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
